import { Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='overflow-x-hidden overflow-y-scroll font-primary'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
